# Generated by Django 3.1.1 on 2020-09-02 10:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20200902_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='services', verbose_name='Image'),
        ),
    ]
